#!/bin/bash

if [ $# -ne 1 ]; then
   echo "newscript needs one argument"
fi
scriptlocation='~/Documents/Git/ProgrammingEnvironments/LinuxScripts'
cd "$scriptlocation"
filename="${1}-script"
filelocation="$scriptlocation/$filename"

echo -e '#!/bin/bash\n\n' > $filename
chmod u+x $filename
echo "alias ${1}='$filelocation'"
vi $filename
